apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-repos.yaml
- cert-manager.yaml
- kube-prometheus-stack.yaml
- loki.yaml
- fluent-bit.yaml
- jaeger.yaml
- otel-operator.yaml
